[project]
name = "ewm-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.7.1",
    "mkdocs-awesome-pages-plugin>=2.10.0",
]
